# Dockerfile for backend
FROM maven:3.8.1-jdk-8-alpine AS MAVEN_BUILD
WORKDIR /tmp/
COPY pom.xml .
COPY src ./src/
RUN mvn package -DskipTests
 
FROM tomcat:9.0-jre8-alpine
COPY --from=MAVEN_BUILD /tmp/target/eschool.jar eschool.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "eschool.jar"]

ARG DATASOURCE_URL
ARG DATASOURCE_USERNAME
ARG DATASOURCE_PASSWORD
ENV DATASOURCE_URL=$DATASOURCE_URL
ENV DATASOURCE_USERNAME=$DATASOURCE_USERNAME
ENV DATASOURCE_PASSWORD=$DATASOURCE_PASSWORD
